server:
  port: 8090
  servlet:
    context-path: /study

spring:
  datasource:
   db1:
     type: mysql
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
     username: root
     password: 1
     testQuery: select 1
     minPoolSize: 3
     maxPoolSize: 25
     maxLifetime: 20000
     borrowConnectionTimeout: 30
     loginTimeout: 30
     maintenanceInterval: 60
     maxIdleTime: 60
   db2:
     type: oracle
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
     username: HIS
     password: 1
     testQuery: select 1  from dual
     minPoolSize: 3
     maxPoolSize: 25
     maxLifetime: 20000
     borrowConnectionTimeout: 30
     loginTimeout: 30
     maintenanceInterval: 60
     maxIdleTime: 60

logging:
  config: classpath:logback.xml

  configuration: #数据库下划线
    map-underscore-to-camel-case: true


LoginPremission: false # 是否开启登录验证
